project_id = "rsfieaipypagioylevbp"

[functions.admin-users]
verify_jwt = false

[functions.send-notifications]
verify_jwt = false

[functions.send-mailing]
verify_jwt = false

[functions.confirm-purchase]
verify_jwt = false

[functions.partner-callback]
verify_jwt = false

[functions.fetch-partner-offers]
verify_jwt = false

[functions.tradedoubler-sync]
verify_jwt = false
