// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-offers.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var search_offers_default = defineTool({
  name: "search_offers",
  title: "Wyszukaj oferty",
  description: "Szuka najlepszych ofert produktowych z wynagrodzeniem (cashback) u partner\xF3w zintegrowanych z netszukacz.pl. Zwraca list\u0119 ujednolicon\u0105 i posortowan\u0105 po cenie efektywnej.",
  inputSchema: {
    query: z.string().min(2).max(100).describe("Fraza wyszukiwania, np. 'iPhone 15'."),
    limit: z.number().int().min(1).max(50).optional().describe("Maksymalna liczba wynik\xF3w (domy\u015Blnie 20)."),
    sort: z.enum(["price_effective", "price", "cashback", "rating"]).optional().describe("Kolejno\u015B\u0107 sortowania. Domy\u015Blnie 'price_effective' (najni\u017Csza cena po cashbacku).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ query, limit, sort }) => {
    const projectRef = globalThis.process?.env?.VITE_SUPABASE_PROJECT_ID || "rsfieaipypagioylevbp";
    const url = `https://${projectRef}.supabase.co/functions/v1/search-offers`;
    const res = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ query, limit: limit ?? 20, sort: sort ?? "price_effective" })
    });
    if (!res.ok) {
      const text = await res.text();
      return {
        content: [{ type: "text", text: `B\u0142\u0105d wyszukiwarki (${res.status}): ${text}` }],
        isError: true
      };
    }
    const data = await res.json();
    const offers = (data.offers ?? []).map((o) => ({
      title: o.title,
      partner: o.partner_id,
      price: o.price_total,
      currency: o.currency,
      cashback_rate: o.cashback_rate,
      cashback_amount: o.cashback_amount,
      price_effective: o.price_effective,
      rating: o.rating,
      url: o.product_url,
      image: o.image_url
    }));
    return {
      content: [
        {
          type: "text",
          text: offers.length === 0 ? `Brak wynik\xF3w dla "${query}".` : `Znaleziono ${offers.length} ofert dla "${query}" (sort: ${sort ?? "price_effective"}).`
        }
      ],
      structuredContent: { query, count: offers.length, offers }
    };
  }
});

// src/lib/mcp/tools/list-rewards.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
import { z as z2 } from "npm:zod@^4.4.3";
var list_rewards_default = defineTool2({
  name: "list_rewards",
  title: "Lista nagr\xF3d",
  description: "Zwraca list\u0119 nagr\xF3d dost\u0119pnych do wymiany za punkty w programie lojalno\u015Bciowym netszukacz.pl.",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).optional().describe("Maksymalna liczba nagr\xF3d (domy\u015Blnie 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const env = globalThis.process?.env ?? {};
    const url = env.SUPABASE_URL || "https://rsfieaipypagioylevbp.supabase.co";
    const key = env.SUPABASE_PUBLISHABLE_KEY || env.SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzZmllYWlweXBhZ2lveWxldmJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA2NjY4NzMsImV4cCI6MjA4NjI0Mjg3M30.jSWFy1LoKw1hSBnsNQaLx_ud-rYyV0Frc1R3mCV--OA";
    const supabase = createClient(url, key, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("rewards").select("id, name, description, points_cost, stock, image_url, category").eq("active", true).order("points_cost", { ascending: true }).limit(limit ?? 25);
    if (error) {
      return {
        content: [{ type: "text", text: `B\u0142\u0105d pobierania nagr\xF3d: ${error.message}` }],
        isError: true
      };
    }
    return {
      content: [
        {
          type: "text",
          text: `Dost\u0119pnych nagr\xF3d: ${data?.length ?? 0}.`
        }
      ],
      structuredContent: { count: data?.length ?? 0, rewards: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "netszukacz-mcp",
  title: "netszukacz.pl MCP",
  version: "0.1.0",
  instructions: "Narz\u0119dzia netszukacz.pl \u2013 por\xF3wnywarki ofert z wynagrodzeniem (cashback). U\u017Cyj `search_offers`, aby znale\u017A\u0107 najlepsze oferty produktowe z partner\xF3w (Allegro, AliExpress, Amazon, Temu) posortowane po cenie efektywnej. U\u017Cyj `list_rewards`, aby pobra\u0107 list\u0119 nagr\xF3d dost\u0119pnych w programie lojalno\u015Bciowym.",
  tools: [search_offers_default, list_rewards_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
